### ISSUE TITLE
"Default" subnetwork in config.xml is configured in the wrong format and the rest of my subnets don't even appear in the drop down

### ISSUE THREAD

**Issue by jhartnett** [jenkinsci/google-compute-engine-plugin#106]
After setting up the plugin using the 'default' subnet, I got the error `Invalid value for field 'resource.networkInterfaces[0]': '{  \"accessConfig\": [{    \"type\": \"ONE_TO_ONE_NAT\",    \"name\": \"External NAT\"  }]}'. Subnetwork should be specified for custom subnetmode network"`when trying to add a slave. On the Jenkins server, I went to the config.xml and found `<networkConfiguration class="com.google.jenkins.plugins.computeengine.AutofilledNetworkConfiguration">
            <network>https://www.googleapis.com/compute/v1/projects/zoominfo-2/global/networks/default</network>
            <subnetwork>default</subnetwork>`
I manually updated the subnetwork part to `<subnetwork>https://www.googleapis.com/compute/v1/projects/zoominfo-2/regions/us-east1/subnetworks/default</subnetwork>`, reloaded the config in the Jenkins UI and everything worked fine. Then I updated the config in the UI and the config reverted back. I also wanted to use a different subnet, but 'default' was the only option.

**Comment by rachely3n** [comment]
How did you set up the network in the first place?

**Comment by rachely3n** [comment]
Update?

**Comment by jhartnett** [comment]
That's a pretty vague question. How did I set up the network in Google? How did I set up network in the Jenkins plugin config? What information are you looking for?

**Comment by rachely3n** [comment]
Are you setting it up via the UI in the instance configuration form? Using JCasC?
With the UI, there are auto-populated options that should work out of the box.

**Comment by rachely3n** [comment]
Also, it would also help for me to see what your instance configuration is.

**Comment by jhartnett** [comment]
I set set up the network in the Jenkins UI. It does have a drop down for subnetworks but the only that appears is 'default'. There aren't any other options.

The instance is Centos7 n1-standard-4. The service account has 'Compute Network Admin'.

![Screenshot at Jun 03 14-17-54](https://user-images.githubusercontent.com/25866868/58824597-714a4b00-860a-11e9-871e-9f2016b71464.png)

**Comment by rachely3n** [comment]
https://github.com/jenkinsci/google-compute-engine-plugin/blob/8478452ad006be07557869418050e063cf9ac8e8/src/test/java/com/google/jenkins/plugins/computeengine/integration/ITUtil.java#L103-L104

If you see there, it seems what is in your config matches values we use for integration testing.

@stephenashank can you take a look?

**Comment by jhartnett** [comment]
When I tried to bring in a new slave, I would get this error: 

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network",
    "reason" : "invalid"
  } ],
  "message" : "Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network"
}

**Comment by stephenashank** [comment]
I was able to reproduce your problem in the UI: even when I had created a new subnetwork under the default network, it was not showing up in the list despite the service account having the Compute Network Admin role. 

So I looked closer and realized that as it stands now, selecting the default subnetwork is required when default is chosen as the network, because no additional items are retrieved, we just assume that default will be used:  https://github.com/jenkinsci/google-compute-engine-plugin/blob/ce5761e444285a877ef8d23cf0c528ae004fc588/src/main/java/com/google/jenkins/plugins/computeengine/AutofilledNetworkConfiguration.java#L104-L107

**Comment by rachely3n** [comment]
Weird, how did you reproduce that? It works fine for me in the UI.

**Comment by stephenashank** [comment]
I was only able to see subnetworks that were not default when I removed the block above.

To reproduce I did this: in cloud console, select **VPC network** then **VPC networks** and click on the *default* network. Then click *Add subnet* to create a custom subnet. Make sure to add it to the region that you are using for configuration, and choose any IP range that is allowed.

Then, I reopened the Jenkins configuration which already had the default network selected, and clicked on the dropdown. I expected to see both of the subnets for the network and region (default and the one I created) but only saw default.

**Comment by rachely3n** [comment]
Should be fixed as soon as we issue the next release.

**Comment by rachely3n** [comment]
Cut a release! Let me know how it goes @jhartnett. It is release 3.3.0.

**Comment by yuri-sergiichuk** [comment]
I do have a concern about the current implementation because after updating to the latest v3.3.0 I receive the following response from the plugin while trying to start a slave:
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'No subnetworks exist in the given network and region.'. The URL is malformed.",
    "reason" : "invalid"
  } ],
  "message" : "Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'No subnetworks exist in the given network and region.'. The URL is malformed."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.jenkins.plugins.computeengine.client.ComputeClient.insertInstance(ComputeClient.java:359)
	at com.google.jenkins.plugins.computeengine.InstanceConfiguration.provision(InstanceConfiguration.java:284)
	at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.doProvision(ComputeEngineCloud.java:411)
```

In my project, I still have a `Legacy VPC network` and thus there are no dedicated sub-networks in it. I have downgraded the plugin version to v3.2.0 to be able to start slaves again.

**Comment by craigdbarber** [comment]
@stephenashank it looks like the previous PR which was submitted for this issue is not interfering with customers using legacy VPCs. Could you PTAL. Thanks.

**Comment by stephenashank** [comment]
I was able to track down the issue:
https://github.com/jenkinsci/google-compute-engine-plugin/blob/bc082bd832e83b0620772b3b7ea7e1f3b06e01a3/src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java#L489-L492

Previously when using a legacy VPC, I'm guessing the default subnetwork would be used in the NetworkConfiguration for the instance, and then in the block above when constructing the network interface, the subnetwork would be omitted. I should be able to fix this by allowing users to select an empty value for subnetwork, and then omitting it from the network interface in that case as well. Does that work for your use case @yuri-sergiichuk?

**Comment by yuri-sergiichuk** [comment]
In my case, with the plugin v3.2.0, the subnetwork is automatically set to `default`. Is it what you're asking?

**Comment by stephenashank** [comment]
Yes that answered my question. The behavior should be restored for legacy VPCs with release 3.3.2 which was just deployed. It can take up to 8 hours to reach the update center, so please check that out when you can.

**Comment by stephenashank** [comment]
@yuri-sergiichuk Was your issue resolved?

**Comment by yuri-sergiichuk** [comment]
@stephenashank yep! Thanks for your efforts and sorry for being late with the response.

**Comment by stephenashank** [comment]
No worries. In that case I will close this out.
